import re
import sys
import json

sys.stdout.reconfigure(encoding='utf-8')

raw_text_file = r"d:\app\alkitab\scratch\full_raw_text.txt"

with open(raw_text_file, "r", encoding="utf-8") as f:
    text = f.read()

# Let's do initial global cleanups of common PDF extraction artifacts
# 1. Join hyphenated words across lines
text = re.sub(r'(\w+)-\n\s*(\w+)', r'\1\2', text)
# 2. Fix spaced-out words commonly generated by the PDF extractor
spaced_words = {
    r'\bY\s+esus\b': 'Yesus',
    r'\bT\s+uhan\b': 'Tuhan',
    r'\bA\s+llah\b': 'Allah',
    r'\bG\s+ereja\b': 'Gereja',
    r'\bT\s+radisi\b': 'Tradisi',
    r'\bP\s+utra\b': 'Putra',
    r'\bK\s+ristus\b': 'Kristus',
    r'\bK\s+atekismus\b': 'Katekismus',
    r'\bK\s+ompendium\b': 'Kompendium',
    r'\bS\s+yahadat\b': 'Syahadat',
    r'\bS\s+akramen\b': 'Sakramen',
    r'\bM\s+aria\b': 'Maria',
    r'\bB\s+apa\b': 'Bapa',
    r'\bR\s+oh\b': 'Roh',
    r'\bK\s+udus\b': 'Kudus',
    r'\bT\s+ritunggal\b': 'Tritunggal',
    r'\bM\s+esia\b': 'Mesia',
    r'\bA\s+postolik\b': 'Apostolik',
    r'\bP\s+erjanjian\b': 'Perjanjian',
    r'\bK\s+itab\b': 'Kitab',
    r'\bS\s+uci\b': 'Suci',
    r'\bU\s+skup\b': 'Uskup',
    r'\bI\s+mam\b': 'Imam',
    r'\bK\s+onsili\b': 'Konsili',
    r'\bV\s+atikan\b': 'Vatikan',
    r'\bM\s+usa\b': 'Musa',
    r'\bA\s+dam\b': 'Adam',
    r'\bH\s+awa\b': 'Hawa',
    r'\bS\s+etan\b': 'Setan',
    r'\bD\s+osa\b': 'Dosa',
    r'\bI\s+man\b': 'Iman',
    r'\bE\s+karisti\b': 'Ekaristi',
    r'\bK\s+omuni\b': 'Komuni',
    r'\bP\s+embaptisan\b': 'Pembaptisan',
    r'\bS\s+engsara\b': 'Sengsara',
    r'\bW\s+afat\b': 'Wafat',
    r'\bK\s+ebangkitan\b': 'Kebangkitan',
    r'\bK\s+erajaan\b': 'Kerajaan',
    r'\bL\s+iturgi\b': 'Liturgi',
    r'\bK\s+asih\b': 'Kasih',
    r'\bH\s+ukum\b': 'Hukum',
    r'\bM\s+oral\b': 'Moral',
    r'\bD\s+oa\b': 'Doa',
    r'\bA\s+min\b': 'Amin',
    r'\bT\s+erlebih\b': 'Terlebih',
    r'\bT\s+erbitnya\b': 'Terbitnya',
    r'\bT\s+erdiri\b': 'Terdiri',
    r'\bT\s+erhadap\b': 'Terhadap',
    r'\bT\s+erutama\b': 'Terutama',
    r'\bT\s+erlepas\b': 'Terlepas',
    r'\bT\s+erputus\b': 'Terputus',
    r'\bT\s+eratur\b': 'Teratur',
    r'\bT\s+ercinta\b': 'Tercinta',
    r'\bT\s+erberkati\b': 'Terberkati',
    r'\bT\s+ertentu\b': 'Tertentu',
    r'\bT\s+erjalannya\b': 'Terjalannya',
    r'\bT\s+erjadi\b': 'Terjadi',
    r'\bT\s+erlaksana\b': 'Terlaksana',
    r'\bT\s+radisional\b': 'Tradisional',
    r'\bw\s+aktu\b': 'waktu',
    r'\bW\s+aktu\b': 'Waktu'
}
for pattern, replacement in spaced_words.items():
    text = re.sub(pattern, replacement, text)

# Let's find matches of: (\d+)\.\s+(.*?)(?=\n|$)
matches = list(re.finditer(r'(\d+)\.\s+(.*?)(?=\n|$)', text))

def is_italian(s):
    italian_words = ["qual", "disegno", "dell", "perche", "desiderio", "ragione", "mistero", "rivelazione", "basta", "luce", "nell", "con", "alla", "sola", "creazione", "mondo", "uomo", "dio", "fede", "chiesa", "padre", "figlio", "spirito", "santo", "peccato", "salvezza", "sacramento", "liturgia", "morale", "preghiera"]
    s_lower = s.lower()
    matches = 0
    for w in italian_words:
        if re.search(r'\b' + w + r'\b', s_lower):
            matches += 1
    return matches >= 2

questions_db = {}
for idx, m in enumerate(matches):
    num = int(m.group(1))
    q_line = m.group(2).strip()
    
    if not (1 <= num <= 598):
        continue
        
    if is_italian(q_line) or "disegno di dio" in q_line.lower() or "desiderio di dio" in q_line.lower() or "della ragione" in q_line.lower() or "luce della" in q_line.lower():
        continue
        
    if num in questions_db:
        continue
        
    start_pos = m.end()
    end_pos = len(text)
    for next_m in matches[idx+1:]:
        next_num = int(next_m.group(1))
        next_q_line = next_m.group(2).strip()
        if 1 <= next_num <= 598 and not (is_italian(next_q_line) or "disegno di dio" in next_q_line.lower() or "desiderio di dio" in next_q_line.lower() or "della ragione" in next_q_line.lower()):
            end_pos = next_m.start()
            break
            
    answer_block = text[start_pos:end_pos].strip()
    
    # Let's clean up common headers and trailing page markers from the answer_block
    # Remove lines like " === PAGE X ===" or "Bagian Satu", "Seksi Dua", page numbers, etc.
    lines = answer_block.split('\n')
    cleaned_lines = []
    for line in lines:
        l_strip = line.strip()
        # Skip empty lines, page headers, Italian artifacts, etc.
        if not l_strip:
            continue
        if l_strip.startswith("=== PAGE"):
            continue
        if l_strip.startswith("Kompendium"):
            continue
        if re.match(r'^\d+$', l_strip): # isolated page numbers
            continue
        if l_strip in ["Bagian Satu", "Bagian Dua", "Bagian Tiga", "Bagian Empat", "Seksi Satu", "Seksi Dua", "BAB SATU", "BAB DUA", "BAB TIGA", "BAB EMPAT"]:
            continue
        if is_italian(l_strip):
            continue
        # Skip margins reference lists (which are just list of numbers on their own lines, e.g. "1-25", "30", "27-30")
        if re.match(r'^[\d\s,-]+$', l_strip) and len(l_strip) < 15:
            continue
        cleaned_lines.append(line)
        
    final_answer = "\n".join(cleaned_lines).strip()
    
    # 3. Clean trailing quotes or index lines at the end of answers
    # Often St. Augustine or other saints quotes appear at the end of pages.
    # Let's remove lines starting with Saint names if they feel like stray page elements
    # But wait, saint quotes are beautiful. Let's keep them if they are part of the answer,
    # but strip off table of contents index headers or watermark lines.
    
    questions_db[num] = {
        "question": q_line,
        "answer": final_answer
    }

print(f"Cleaned and parsed {len(questions_db)} unique Q&As.")

# Map questions to pillars and write JSON
pillars = {
    "syahadat": {"range": (1, 217), "title": "Pilar 1: Pengakuan Iman (Syahadat)", "color": "from-blue-700 to-cyan-600"},
    "sakramen": {"range": (218, 356), "title": "Pilar 2: Perayaan Misteri Kristen (Sakramen)", "color": "from-amber-600 to-orange-500"},
    "moral": {"range": (357, 533), "title": "Pilar 3: Hidup dalam Kristus (Moralitas)", "color": "from-emerald-700 to-teal-600"},
    "doa": {"range": (534, 598), "title": "Pilar 4: Doa Kristen (Bapa Kami)", "color": "from-purple-700 to-pink-600"}
}

structured_database = []
for p_id, p_info in pillars.items():
    p_questions = []
    start, end = p_info["range"]
    for i in range(start, end + 1):
        if i in questions_db:
            p_questions.append({
                "id": i,
                "question": questions_db[i]["question"],
                "answer": questions_db[i]["answer"],
                "reference": f"KGK {i}", # Fallback, we can refine this later
                "reflection": "" # Placeholder, we will populate with deep reflections
            })
    structured_database.append({
        "pillar": p_id,
        "pillarTitle": p_info["title"],
        "color": p_info["color"],
        "questions": p_questions
    })

output_json = r"d:\app\alkitab\scratch\cleaned_raw_compendium.json"
with open(output_json, "w", encoding="utf-8") as f:
    json.dump(structured_database, f, ensure_ascii=False, indent=2)

print(f"Structured database written to {output_json}")
